//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArduinoConn.LOCALDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtificialIntelligence
    {
        public long ID { get; set; }
        public string AverageTemperature { get; set; }
        public string Lights { get; set; }
        public string NightStart { get; set; }
        public string DayStart { get; set; }
        public string Year { get; set; }
        public string Week { get; set; }
        public string Day { get; set; }
        public string Damp { get; set; }
    }
}
