//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArduinoConn.LOCALDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtificialIntelligence
    {
        public long ID { get; set; }
        public Nullable<double> AverageTemperature { get; set; }
        public string Lights { get; set; }
        public Nullable<decimal> NightStart { get; set; }
        public Nullable<decimal> DayStart { get; set; }
        public Nullable<decimal> Year { get; set; }
        public Nullable<decimal> Week { get; set; }
        public Nullable<decimal> Day { get; set; }
        public Nullable<double> Damp { get; set; }
    }
}
