//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArduinoConn.LOCALDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainLog
    {
        public long ID { get; set; }
        public Nullable<double> Temperature { get; set; }
        public string Light { get; set; }
        public Nullable<decimal> Time { get; set; }
        public Nullable<decimal> Month { get; set; }
        public Nullable<decimal> Days { get; set; }
        public Nullable<decimal> Years { get; set; }
        public Nullable<double> Damp { get; set; }
    }
}
