//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArduinoConn.LOCALDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainLog
    {
        public long ID { get; set; }
        public string Temperature { get; set; }
        public string Light { get; set; }
        public string Time { get; set; }
        public string Month { get; set; }
        public string Days { get; set; }
        public string Years { get; set; }
        public string Damp { get; set; }
    }
}
